*** Settings ***
Library     SeleniumLibrary
Resource    ../../../../../../../002Web/Resources/000-Common/CommonVariables.robot

*** Variables ***
${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY}     ${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_DIC.${LANGUAGE}}
${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_EN}    Checkout
${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_AR}     الدفع
&{POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_DIC}        en= ${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_EN}    ar=${POST_CHECKOUT_PAGE_CHECKOUT_TEXT_APPEAR_SUCCESSFULLY_AR}


${POST_CHECKOUT_PAGE_WALLET_RADIO_BUTTON_APPEAR_SUCCESSFULLY}     xpath=/html/body/div[6]/div/div/div/form/div[1]/label[2]/span
${POST_CHECKOUT_CREATED_POST_BY_WALLET_SUCCESSFULL_MSG_APPEAR}     xpath=/html/body/div[6]/div/div/div/form/div[1]/label[2]/span
