*** Settings ***
Library     SeleniumLibrary
Resource    ../000-Common/CommonVariables.robot


*** Variables ***

${HEADER_LOGIN_DIALOG_TEXT}               ${HEADER_LOGIN_DIALOG_TEXT_DIC.${LANGUAGE}}
${HEADER_LOGIN_DIALOG_TEXT_EN}                    Login
${HEADER_LOGIN_DIALOG_TEXT_AR}                    تسجيل الدخول
&{HEADER_LOGIN_DIALOG_TEXT_DIC}              en=${HEADER_LOGIN_DIALOG_TEXT_EN}    ar=${HEADER_LOGIN_DIALOG_TEXT_AR}


${HEADER_SUGGESTIONS_DIALOG_TEXT}               ${HEADER_SUGGESTIONS_DIALOG_TEXT_DIC.${LANGUAGE}}
${HEADER_SUGGESTIONS_DIALOG_TEXT_EN}                    Suggestions
${HEADER_SUGGESTIONS_DIALOG_TEXT_AR}                    اقتراحات
&{HEADER_SUGGESTIONS_DIALOG_TEXT_DIC}              en=${HEADER_SUGGESTIONS_DIALOG_TEXT_EN}    ar=${HEADER_SUGGESTIONS_DIALOG_TEXT_AR}


${HEADER_OTP_DIALOG_TEXT}               ${HEADER_OTP_DIALOG_TEXT_DIC.${LANGUAGE}}
${HEADER_OTP_DIALOG_TEXT_EN}                    OTP
${HEADER_OTP_DIALOG_TEXT_AR}                    الرقم السري المؤقت
&{HEADER_OTP_DIALOG_TEXT_DIC}              en=${HEADER_OTP_DIALOG_TEXT_EN}    ar=${HEADER_OTP_DIALOG_TEXT_AR}

${OTP_INVALID_TEXT}               ${OTP_INVALID_TEXT_DIC.${LANGUAGE}}
${OTP_INVALID_TEXT_EN}                    Invalid otp
${OTP_INVALID_TEXT_AR}                    كلمة مرور لمرة واحدة غير صالحة
&{OTP_INVALID_TEXT_DIC}              en=${OTP_INVALID_TEXT_EN}    ar=${OTP_INVALID_TEXT_AR}

${HEADER_COMPLETE_PROFILE_DIALOG_TEXT}               ${HEADER_COMPLETE_PROFILE_DIALOG_TEXT_DIC.${LANGUAGE}}
${HEADER_COMPLETE_PROFILE_DIALOG_TEXT_EN}                    Complete your account
${HEADER_COMPLETE_PROFILE_DIALOG_TEXT_AR}                       أكمل حسابك
&{HEADER_COMPLETE_PROFILE_DIALOG_TEXT_DIC}              en=${HEADER_COMPLETE_PROFILE_DIALOG_TEXT_EN}    ar=${HEADER_COMPLETE_PROFILE_DIALOG_TEXT_AR}

${HEADER_CREATE_NEW_ACCOUNT_TEXT}               ${HEADER_CREATE_NEW_ACCOUNT_TEXT_DIC.${LANGUAGE}}
${HEADER_CREATE_NEW_ACCOUNT_TEXT_EN}                    Create new account
${HEADER_CREATE_NEW_ACCOUNT_TEXT_AR}                    إنشاء حساب جديد
&{HEADER_CREATE_NEW_ACCOUNT_TEXT_DIC}              en=${HEADER_CREATE_NEW_ACCOUNT_TEXT_EN}    ar=${HEADER_CREATE_NEW_ACCOUNT_TEXT_AR}


${VALIDATION_INVALID_NUMBER_TEXT}               ${VALIDATION_INVALID_NUMBER_TEXT_DIC.${LANGUAGE}}
${VALIDATION_INVALID_NUMBER_TEXT_EN}                    The mobile format is invalid
${VALIDATION_INVALID_NUMBER_TEXT_AR}                    صيغة الجوال .غير صحيحة
&{VALIDATION_INVALID_NUMBER_TEXT_DIC}              en=${VALIDATION_INVALID_NUMBER_TEXT_EN}    ar=${VALIDATION_INVALID_NUMBER_TEXT_AR}

${RESEND_OTP_BUTTON_TEXT}               ${VALIDATION_INVALID_NUMBER_TEXT_DIC.${LANGUAGE}}
${VALIDATION_INVALID_NUMBER_TEXT_EN}                    Resend code
${VALIDATION_INVALID_NUMBER_TEXT_AR}                    صيغة الجوال .غير صحيحة
&{VALIDATION_INVALID_NUMBER_TEXT_DIC}              en=${VALIDATION_INVALID_NUMBER_TEXT_EN}    ar=${VALIDATION_INVALID_NUMBER_TEXT_AR}